---
- name: tar it all
  hosts: localhost
  tasks:
    - name: create mirror dir
      file:
        path: "{{ archive_root }}/httpd/"
        state: directory
      tags: tar
    
    - name: archive it
      shell: "tar -cf archive.{{ansible_date_time.date}}.tar ../gitrepos/ ../images/"
      args:
          chdir: "{{ archive_root }}/httpd"
      tags: tar

    - name: perms
      file:
        dest: "{{ archive_root }}/httpd/"
        owner: 'root'
        mode: 'u=rwX,g=rX,o=rX'
        recurse: 'yes'
    
