---
- name: tar it all
  hosts: localhost
  vars: 
    import_root: '/var/lib/import'
  tasks:
    - name: clear work dir
      file:
        path: "{{ import_root }}/tar_tmp"
        state: absent
      tags: tar
      
    - name: create work dir
      file:
        path: "{{ import_root }}/tar_tmp"
        state: directory
      tags: tar

    - name: archive it
      #shell: "tar -cf images-{{ansible_date_time.date}}.tar ../images/ ../ocp-release ../wget/"
      shell: "tar -cf images-{{ansible_date_time.date}}.tar ../images/"
      args:
        chdir: "{{ import_root }}/tar_tmp"
      tags: tar

    - name: copy to export
      shell: "mv {{ import_root }}/tar_tmp/* {{ export_dir }}"

#    - name: perms
#      file:
#        dest: "{{ export_dir}}"
#        owner: 'root'
#        mode: 'u=rwX,g=rX,o=rX'
#        recurse: 'yes'
#    
