---
- hosts: ocp4
  gather_facts: True
  tags: 
    - ocp
  vars:
    # coreos boot media doesnt have point releases, once 4.3 is out its not updated till 4.4
    ocp_tag: '4.6.20'
    coreos_tag: '4.6.8'
    ocp_ver: '4.6'
    bin_path: "{{ import_root }}/bin"
    registry_path: "{{ import_root}}/registry"
    release_path: "{{import_root}}/ocp-release"
    olm_dir: "{{import_root}}/olm"
    # get pull secret from https://cloud.redhat.com/openshift/install/metal/user-provisioned
    auth_file: "/var/lib/import/plays/auth.json"
    operator_indexes: 
    # see https://access.redhat.com/support/cases/#/case/02729981
      - name: 'redhat-operator'
        image: "registry.redhat.io/redhat/redhat-operator-index@sha256:795401324fa1482361d5af7080378cf6abc5d31a26c4166d8b6af14978af1754"
          # - name: 'certified-operator'
          # image: "registry.redhat.io/redhat/certified-operator-index@sha256:3ec2a292197c45f1c3f28e19579ae0df0a7764efc6ca997b40ef6ec2a05f862e"
#      - name: 'community-operator'
#        image: "registry.redhat.io/redhat/community-operator-index@sha256:59cc56d927637850dbeea69f55e6ad28d3b634695db23f71089fcd16199f8ffc"
      #- name: 'redhat-marketplace'
      #  image: "registry.redhat.io/redhat/redhat-marketplace-index:v{{ocp_ver}}"
  pre_tasks:
    - name: facts
      setup:
      tags: always
  tasks:
    - name: create paths
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      loop:
        - "{{ bin_path }}"
        - "{{ release_path }}"
        - "{{ olm_dir }}"
        - "{{ import_root }}/wget"
        - "{{ registry_path }}"
      tags: init
    - name: grab coreos media
      command: "/bin/wget --recursive --directory-prefix {{import_root}}/wget --cut-dirs 1 -R 'index.html*,*nightly*' -np {{ item }}"
      loop:
        - "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/{{ ocp_ver }}/{{coreos_tag}}/rhcos-openstack.x86_64.qcow2.gz"
        - "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/{{ ocp_ver }}/{{coreos_tag}}/rhcos-metal.x86_64.raw.gz"
        - "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/{{ ocp_ver }}/{{coreos_tag}}/rhcos-live-initramfs.x86_64.img"
        - "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/{{ ocp_ver }}/{{coreos_tag}}/rhcos-live-kernel-x86_64"
        - "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/{{ ocp_ver }}/{{coreos_tag}}/rhcos-live-rootfs.x86_64"
        - "https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/{{ ocp_ver }}/{{coreos_tag}}/rhcos-live.x86_64.iso"
        - "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocp_tag }}/openshift-client-linux-{{ocp_tag}}.tar.gz"
        - "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocp_tag }}/openshift-client-windows-{{ocp_tag}}.zip"
        - "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ ocp_tag }}/openshift-install-linux-{{ocp_tag}}.tar.gz"
        - "http://mirror.openshift.com/pub/openshift-v4/clients/opm/4.6.1/opm-linux-4.6.1.tar.gz"
      tags: wget,binary
    - name: extract binary
      unarchive:
        src: "{{ item }}"
        dest: "{{bin_path}}"
      loop:
        - "{{import_root}}/wget/mirror.openshift.com/openshift-v4/clients/ocp/{{ocp_tag}}/openshift-client-linux-{{ocp_tag}}.tar.gz"
        - "{{import_root}}/wget/mirror.openshift.com/openshift-v4/clients/ocp/{{ocp_tag}}/openshift-install-linux-{{ocp_tag}}.tar.gz"
        - "{{import_root}}/wget/mirror.openshift.com/openshift-v4/clients/opm/4.6.1/opm-linux-4.6.1.tar.gz"
      tags: binary
    - name: get ocp4 images
      shell: "{{bin_path}}/oc adm -a {{auth_file}} release mirror  quay.io/openshift-release-dev/ocp-release:{{ocp_tag}}-x86_64 --to-dir {{release_path}}"
      tags: 
        - ocp-release
      register: release_mirror
    # see https://github.com/ansible/ansible/issues/56243#issuecomment-562657109
    - name: deal with copy bug
      file:
        path: "{{release_path}}/mirror.out"
        state: touch
    - name: preserve mirror output for high side
      copy:
        content: "{{release_mirror}}"
        dest: "{{release_path}}/mirror.out"
      tags: ocp-release
    - name: clear cache
      file:
        path: "{{olm_dir}}/{{item.name}}"
        state: absent
        force: yes
      loop: "{{ operator_indexes }}"
      tags: olm
    - name: clear cache
      file:
        path: "{{olm_dir}}/{{item.name}}/image"
        state: directory
      loop: "{{ operator_indexes }}"
      tags: olm
    - name: mirror indexes
      shell: "skopeo copy docker://{{item.image}} docker://{{mirror_registry}}/ocp-release/{{item.name}}:{{ocp_tag}}"
      loop: "{{ operator_indexes }}"
      tags: 
        - olm
    - name: mirror catalog refs
      shell: "{{bin_path}}/oc adm catalog mirror {{item.image}} {{mirror_registry}}/{{item.name}} -a {{auth_file}} --filter-by-os=.* --icsp-scope=registry --to-manifests={{olm_dir}}/{{item.name}}"
      tags: 
        - olm
      loop: "{{ operator_indexes}}"
    - name: mirror images
      shell: |
        awk -F '[/=@:]' '{ if (NF==10) system("skopeo copy --all docker://"$1"/"$2"/"$3"@sha256:"$5" docker://registry.mirror:5000/"$1"/"$2":"$10" --authfile /var/lib/import/plays/auth.json")}' /var/lib/import/olm/{{item.name}}/mapping.txt 
      tags: olm
      loop: "{{ operator_indexes }}"
