---


- hosts: localhost
  name: mirror helm binaries repos and dependencies
  vars: 
    helm_dir: /var/lib/import/helm/
    export_dir: /var/lib/export/
    cache_dir: "{{helm_dir}}/cache"
    pkg_dir: "{{helm_dir}}/pkgs"
    bin_dir: /var/lib/import/bin
    helm_exe: "{{bin_dir}}/linux-amd64/helm"
    helm_ver: v3.4.0
    repos:
      - name: bitnami
        url: https://charts.bitnami.com/bitnami
        packages: 
          - name: redis
          - name: redis-cluster
          - name: harbor
          - name: kafka
          - name: zookeeper
      - name: yugabytedb
        url: https://charts.yugabyte.com
        packages:
          - name: yugabyte
      - name: ingress-nginx
        url: https://kubernetes.github.io/ingress-nginx
        packages:
          - name: ingress-nginx
      - name: elastic-search
        url: https://helm.elastic.co
        packages:
          - name: apm-server
          - name: elasticsearch
          - name: filebeat
          - name: kibana
          - name: logstash
          - name: metricbeat
      - name: gitlab
        url: https://charts.gitlab.io
        packages:
          - name: gitlab
            args: '--set certmanager-issuer.email=me@example.com'
      - name: minio
        url: https://helm.min.io/
        packages:
          - name: minio
  tasks:
    - name: clear cache
      file:
        path: "{{ helm_dir }}"
        state: absent
    - name: create import dir
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      loop:
        - "{{ bin_dir }}"
        - "{{ helm_dir }}"
        - "{{ cache_dir}}"
        - "{{ pkg_dir}}"
    - name: get binary
      # get_url has selinux issues on latest fedora
      shell:
        cmd: "wget https://get.helm.sh/helm-{{helm_ver}}-linux-amd64.tar.gz"
        chdir: "{{ helm_dir}}"
    - name: extract executable
      unarchive: 
        src: "{{helm_dir}}/helm-{{helm_ver}}-linux-amd64.tar.gz"
        dest: "{{bin_dir}}"
    - name: get helm repos
      shell:
        cmd: "{{helm_exe}} repo add {{ item.name}} {{item.url}} --repository-cache {{cache_dir}}"
      loop: "{{ repos }}" 
      tags: repos
    - name: update cache
      shell:
        cmd: "{{helm_exe}} repo update --repository-cache {{cache_dir}}"
      tags: repos   
    - name: get helm packages
      shell:
        cmd: "{{helm_exe}} fetch {{ item.0.name}}/{{item.1.name }} --repository-cache {{cache_dir}}"
        chdir: "{{pkg_dir}}"
      loop: "{{repos|subelements('packages')}}" 
      tags: repos
    - name: find dependant images
      shell:
        cmd: "{{helm_exe }} template {{item.1.name}}* {{ item.1.args | default('') }} | grep -oP '(?<=image: ).*' | sort | uniq"
        chdir: "{{ pkg_dir }}"
      register: image_depends
      loop: "{{repos|subelements('packages')}}" 
      tags: repos
    - name: find more dependant images
      shell:
        cmd: |
           {{helm_exe}} show values {{item.src}} | yq -r 'flatten | .. | .registry? + "/"? + .repository? + ":"? + .tag?' | grep -v null | sort | uniq | grep -v /: | sed 's/^\///' 
      register: more_image_depends
      with_filetree: "{{pkg_dir}}"
      ignore_errors: yes
      tags: repos
    - name: collect images
      set_fact:
        images_to_mirror: "{{ (images_to_mirror | default([])) + [(item[1]| replace('\"',''))] }}"
      loop: "{{image_depends.results|subelements('stdout_lines')|unique }}"
    - name: collect more images
      set_fact:
        images_to_mirror: "{{ (images_to_mirror | default([])) + [(item[1]| replace('\"',''))] }}"
      loop: "{{more_image_depends.results|subelements('stdout_lines')|unique }}"
    - name:
      debug:
        var: images_to_mirror
        verbosity: 0
      tags: repos

    - name: get images
      shell:
        cmd: "skopeo copy docker://{{item}} docker://{{mirror_registry}}/{{item}}"
      loop: "{{ images_to_mirror |unique }}"
      ignore_errors: yes
      tags: repos
    - name: archive it
      shell: 
        cmd: "tar -cf helm-{{ansible_date_time.date}}.tar ../helm"
        chdir: "{{ export_dir}}"
      tags: tar 

