---

- name: find them all
  hosts: localhost
  pre_tasks:
    - name: load the vars
      include_vars:
        file: "{{ item }}"
      loop:
        - 3.7_defined_images.yml
        - git_repos.yml
  roles:
    - name: openshift-images
      tags: search

- name: get them all
  hosts: localhost
  vars: 
    images_to_archive: "{{ repo_images|union(defined_images) }}"
  pre_tasks:
    - name: what have we got
      debug:
        var: "{{ item }}"
      loop:
        - images_to_archive
        - repo_images
        - defined_images
  roles:
    - container-archive
  tasks:
    - name: grab the gits
      tags: git
      when: grab_git == True
      block:
        - name: clear exisiting git mirrors
          file:
            path: "{{ archive_root }}/gitrepos/"
            state: absent

        - name: create mirror dir
          file:
            path: "{{ archive_root }}/gitrepos/"
            state: directory 

        - name: pull all github
          shell: "git clone --mirror {{ item }}"
          args:
              chdir: "{{ archive_root }}/gitrepos/"
          with_items: "{{ mirrored_git_repos }}"
          
    - name: create mirror dir
      include_tasks: archive.yml
      tags: tar
      when: run_archive == True

