---

- name: get them all
  hosts: localhost
  become: true
  environment:
    http_proxy: http://proxy.defcen.gov.au:8080
    https_proxy: http://proxy.defcen.gov.au:8080
  tasks:
   - name: load triplo vars
     include_vars: ../tripleo-common/container-images/overcloud_containers.yaml
   - name: check docker is running
     service:
       name: docker
       state: started
     tags:
       - docker
   - name: pull all docker
     docker_image:
       name: "{{ item.imagename }}"
       archive_path: "{{ archive_root }}/images/{{ item.imagename|replace('/','_') }}"
     with_items: 
        - "{{ container_images }}"
     register: archive_cmd
     #failed_when: "'No such file or directory' in archive_cmd.std_out.lines"
     failed_when: False
     tags:
       - docker
   - name: archive it
     shell: "tar -cJf triple0.archive.{{ansible_date_time.date}}.tar.xz gitrepos/ images/"
     args:
        chdir: "{{ archive_root }}"
     tags:
        - archive
     failed_when: false



