# coreos boot media doesnt have point releases, once 4.3 is out its not updated till 4.4
ocp_tag: '4.9.29'
coreos_tag: '4.9.0'
ocp_ver: '4.9'
bin_path: "{{ import_root }}/bin"
registry_path: "{{ import_root}}/registry"
release_path: "{{import_root}}/ocp-release/{{ ocp_tag }}"
olm_dir: "{{import_root}}/olm/{{ocp_tag}}"
# get pull secret from https://cloud.redhat.com/openshift/install/metal/user-provisioned
auth_file: "/var/lib/import/plays/auth.json"
operator_indexes: 
  - name: 'redhat-operator'
    image: "registry.redhat.io/redhat/redhat-operator-index:v{{ocp_ver}}"
    packages:
      - ansible-automation-platform-operator
      - cluster-logging
      - clusterresourceoverride
      - codeready-workspaces2
      - costmanagement-metrics-operator
      - devworkspace-operator
      - elasticsearch-operator
      - kubernetes-nmstate-operator
      - kubevirt-hyperconverged
      - local-storage-operator
      - metallb-operator
      - openshift-gitops-operator
      - openshift-jenkins-operator
      - openshift-pipelines-operator-rh
  - name: 'certified-operator'
    image: "registry.redhat.io/redhat/certified-operator-index:v{{ocp_ver}}"
    packages:
      - cilium
      - gitlab-runner-operator
      - gpu-operator-certified
      - hpe-csi-operator
      - minio-operator
      - nginx-ingress-operator
      - openshiftartifactoryha-operator
      - portworx-certified
      - sysdig-certified
        
  - name: 'community-operator'
    image: "registry.redhat.io/redhat/community-operator-index:v{{ocp_ver}}"
    packages:
      - eclipse-che
      - portworkx-essentials
      - oapdp-operator
      - node-healthcheck-operator
      - namespace-configuration-operator
      - keycloak-operator
      - prometheus-exporter-operator
      - argocd-operator

ocp_image_repos:
  - name: 'samples-operator'
    source: "https://github.com/openshift/cluster-samples-operator.git"
    branch: "release-{{ ocp_ver }}"
    files: []
    path: 'assets/operator/ocp-x86_64/'


