# coreos boot media doesnt have point releases, once 4.3 is out its not updated till 4.4
ocp_tag: '4.6.15'
coreos_tag: '4.6.15'
ocp_ver: '4.6'
bin_path: "{{ import_root }}/bin"
registry_path: "{{ import_root}}/registry"
release_path: "{{import_root}}/ocp-release"
olm_dir: "{{import_root}}/olm"
# get pull secret from https://cloud.redhat.com/openshift/install/metal/user-provisioned
quay_creds: "/var/lib/import/plays/auth.json"
operator_orgs:
  - 'redhat-operators'
  - 'certified-operators'
ocp_image_repos:
  - name: 'samples-operator'
    source: "https://github.com/openshift/cluster-samples-operator.git"
    branch: "release-{{ ocp_version }}"
    files: []
    path: 'tmp/build/assets/operator/ocp-x86_64/'

# extra images that are handy
ocp_images:
 #
  - "registry.redhat.io/rhel7/rhel-atomic:latest"
  - "registry.redhat.io/rhel7/rhel:latest"
  - "registry.redhat.io/rhscl/s2i-base-rhel7:latest"
  - "registry.redhat.io/rhscl/s2i-core-rhel7:latest"
  - "registry.redhat.io/openjdk/openjdk-11-rhel7:latest"
  - "registry.redhat.io/openjdk/openjdk-11-rhel8:latest"
  - "registry.redhat.io/openjdk/openjdk-8-rhel8:latest"
  - "registry.access.redhat.com/rhceph/rhceph-3-rhel7:3"
  - "registry.access.redhat.com/rhceph/rhceph-3-dashboard-rhel7:3"

